### ISSUE TITLE
Get discount end date

### ISSUE THREAD

**Issue by wokcito** [xDimGG/node-steamapi#50]
Hi, I was trying to use /appdetails endpoint, but I need know when a game's discount finish.

I tried to figure out how steamdb gets this information but I wasn't able to find the endpoint or the filter that gives this information.

**Comment by xDimGG** [comment]
Max,

After a bit of investigation, it would appear that discount's end date is not provided by the API. If I were to guess, SteamDB scrapes the store page rather than (or maybe as well as) fetching the `/appdetails` endpoint to get that information.

I did find the following resource: https://github.com/m0uka/steam_games_apify

Which scrape the game page and puts that information in a field called `saleUntil`.

Hope that helps.

**Comment by wokcito** [comment]
Thank you so much, I will investigate about it!
